// <auto-generated />
namespace Software2.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-beta1-60406")]
    public sealed partial class changePassword : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(changePassword));
        
        string IMigrationMetadata.Id
        {
            get { return "201709210420165_changePassword"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
