// <auto-generated />
namespace Software2.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class mg2carlos : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(mg2carlos));
        
        string IMigrationMetadata.Id
        {
            get { return "201710260128556_mg2carlos"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
